import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { Suspense } from "react";
import { AlertListener } from "./my/components/subElements/effects/AlertListener";
import { Toaster } from "sonner";

import Settings from "./my/components/Settings";

import "./globals.css";
import { prisma } from "@/lib/prisma";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const config = await prisma.config.upsert({
    where: {id: "global"},
    update: {},
    create: {id: "global", fromNameEnabled: false}
  })

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NextTopLoader
          color="#ffffff"
          height={3}
          showSpinner={false}
        />
        <Suspense fallback={null}>
          <AlertListener />
        </Suspense>
        <Settings intialConfig={config} />
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
